version: "3"

services:
  # Database
  db:
    image: mysql:8.0 
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      default:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: checkers
      MYSQL_PASSWORD: password

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    networks:
      default:
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  # python
  checkers:
    depends_on:
      - db
    image: checkers:latest
    container_name: checkers
    networks:
      default:
    restart: always
    ports:
      - "80:8080"
    build:
      context: .
      dockerfile: Dockerfile

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "10.8.10.0/24"


volumes:
  db_data:
