version: "3"

services:
  # Database
  db:
    image: mysql:8.0 
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: checkers
      MYSQL_PASSWORD: password

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  # python
  checkers:
    depends_on:
      - db
    image: checkers:latest
    container_name: checkers
    restart: always
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  db_data:
